spring.application.name=veebipood
#kui tekib port on juba hõivatud error, siis saab porti muuta: server.port = 8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7l9c2reo5us73dfk260-a.oregon-postgres.render.com/veebipood_database_v41k
spring.datasource.username=veebipood_user
spring.datasource.password=OId053UBNMtn0H7QcmotvYay64WanDxb